// notes actions
const actions = {
  ADD_NOTE: "ADD",
  UPDATE_NOTE_COLOR: "UPDATE_COLOR",
  UPDATE_NOTE_CONTENT: "UPDATE_CONTENT",
  ARCHIVE_NOTE: "ARCHIVE",
  TRASH_NOTE: "TRASH",
  RESTORE_NOTE: "RESTORE",
  DELETE_NOTE: "DELETE",
  TOGGLE_VIEW: "TOGGLE_VIEW",
};
export default actions;
